/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peinture;

import javax.swing.table.DefaultTableModel;
import model.Commande;
import model.QuantiteColori;
import utils.Function;
import utils.GetColori;

/**
 *
 * @author itu
 */
public class AllCommande extends javax.swing.JFrame {

    /**
     * Creates new form AllCommande
     */
    Simuler sim = new Simuler();
    GetColori colo = new GetColori();
    Function fonc = new Function();
    QuantiteColori qc = new QuantiteColori();
    Object[] nom;
    Object[] r;
    Object[] v;
    Object[] b;
    Object[] qu;
    Object[] vo;
    Object[] pr;
    Object[] re;
    public AllCommande() {
        initComponents();
        rempTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listecommande = new javax.swing.JTable();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Commande enregistre:");

        listecommande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(listecommande);

        ok.setText("Commander");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(208, 208, 208))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ok)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ok)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here: 
        instC();
        sim.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_okActionPerformed
    public void instC() {
        int indice = listecommande.getSelectedRow();
        Object noms = listecommande.getModel().getValueAt(indice, 1);
        Object quantites = listecommande.getModel().getValueAt(indice, 2);
        Object rs = listecommande.getModel().getValueAt(indice, 3);
        Object gs = listecommande.getModel().getValueAt(indice, 4);
        Object bs = listecommande.getModel().getValueAt(indice, 5);
        sim.setNomCol().setText(String.valueOf(noms));
        sim.setQuant().setText(String.valueOf(quantites));
        sim.setR().setText(String.valueOf(fonc.getPourcentage(Double.parseDouble(String.valueOf(rs)))));
        sim.setV().setText(String.valueOf(fonc.getPourcentage(Double.parseDouble(String.valueOf(gs)))));
        sim.setB().setText(String.valueOf(fonc.getPourcentage(Double.parseDouble(String.valueOf(bs)))));
    }
    
    
    public void rempTable() {
        Commande[] fer = colo.getAllCommande();
        int f = fer.length;
        String[] columns = null;
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        String[] rep = null;
        nom = new Object[f];
        r = new Object[f];
        v = new Object[f];
        b = new Object[f];
        qu = new Object[f];
        vo = new Object[f];
        int u = 0;
        for (int i = 0; i < f; i++) {

            nom[u] = (Object) fer[i].getNom_commande();
            r[u] = (Object) fer[i].getR();
            v[u] = (Object) fer[i].getG();
            b[u] = (Object) fer[i].getB();
            qu[u] = (Object) fer[i].getQuantite();
            vo[u] = (Object) fer[i].getIdcommande();
            u++;

        }
        listecommande.setModel(model); 
        model.addColumn("id ", vo);
        model.addColumn("Nom", nom);
        model.addColumn("Quantite (kg)", qu);
        model.addColumn("R (%)", r);
        model.addColumn("V (%)", v);
        model.addColumn("B (%)", b);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllCommande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listecommande;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
